name: Tomorrow Partners LLP
favicon: null
layout_spectrum: 0.5329503396060318
typography_spectrum: 0.17392760724760592
title: Tomorrow Partners LLP
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9184245637152344
  lightness: 0.002776145003736019
  saturation: 0.04867054894566536
  rhythmicContrast: 0.3455841653048992
purpose: []
